name: chill_app
description: "ChillApp — Hub central de l'écosystème Chill"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  go_router: ^16.2.2
  shared_preferences: ^2.5.4
  google_fonts: ^8.0.2
  crypto: ^3.0.7
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding/fr/dark/
    - assets/images/onboarding/fr/light/
    - assets/images/onboarding/en/dark/
    - assets/images/onboarding/en/light/
